### ISSUE TITLE
SSL vertify failed

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/role_sqlite#3]
![FLBYR@8N%P4B%C}RDGQ9N8N](https://user-images.githubusercontent.com/43192516/153130426-cfa75c28-c447-4820-9ff8-090d6c7ef855.png)

**Comment by qiaofeng1227** [comment]
```
- name: Download decompression sqlite3 
  unarchive:
    src: '{{sqlite_url}}'
    dest: '{{sqlite_dir}}'
    remote_src: yes
    validate_certs: no(add)
```
